# startup : docker-compose up
# stop : docker-compose stop
# list containers : docker-compose ps
version: '2'
services:
  es:
    image: elasticsearch:5.4.2
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms64m -Xmx64m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata1:/Users/daniel/tmp/es/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: kibana:5.4.2
    environment:
      - ELASTICSEARCH_URL=http://192.168.99.100:9200
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge